---
- name: Install Prometheus and Grafana dependencies
  apt:
    name:
      - prometheus
      - prometheus-node-exporter
      - adduser
      - libfontconfig1
    state: present
    update_cache: yes

- name: Add Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'

- name: Add Grafana repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Configure Grafana to listen on custom port
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;?http_port ='
    line: "http_port = {{ grafana_port }}"
    insertafter: '^\[server\]'

- name: Ensure Grafana is enabled and running
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Ensure Prometheus is enabled and running
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Download Loki binary
  get_url:
    url: "https://github.com/grafana/loki/releases/latest/download/loki-linux-amd64.zip"
    dest: /tmp/loki.zip

- name: Unzip Loki binary
  unarchive:
    src: /tmp/loki.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'