---
- name: Rollback InforceFit Application (1 commit back)
  hosts: webservers
  become: true
  become_user: "{{ app_user }}"

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Revert Git repository to previous commit (Prod)
      command: git reset --hard HEAD~1
      args:
        chdir: "{{ prod_app_dir }}"

    - name: Re-install dependencies with pnpm
      command: pnpm install
      args:
        chdir: "{{ prod_app_dir }}"

    - name: Restart PM2 process
      command: pm2 restart {{ prod_pm2_name }} --update-env