---
- name: Install Nginx and Certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Nginx configuration template
  template:
    src: inforcefit.conf.j2
    dest: /etc/nginx/sites-available/inforcefit.conf
  notify: Reload Nginx

- name: Enable Nginx site for InforceFit
  file:
    src: /etc/nginx/sites-available/inforcefit.conf
    dest: /etc/nginx/sites-enabled/inforcefit.conf
    state: link
  notify: Reload Nginx

- name: Ensure Nginx is running and enabled on boot
  service:
    name: nginx
    state: started
    enabled: yes